# -*- coding: utf-8 -*-
"""
/***************************************************************************
 numerar_lote
                                 A QGIS plugin
 Numerar Loteamento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-01
        copyright            : (C) 2022 by Gloria Santos/Antonio Teles
        email                : mdgss.gloria@gmail.com/antoniot.leandro@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load numerar_lote class from file numerar_lote.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .numerar_lote import numerar_lote
    return numerar_lote(iface)
